# Generated by Django 5.0.2 on 2024-04-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_company', '0002_remove_job_application_form_hire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_application_form',
            name='job_applier',
            field=models.CharField(max_length=25),
        ),
    ]
