# Generated by Django 5.0.2 on 2024-05-03 02:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_company', '0003_alter_job_application_form_job_applier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job_application_form',
            name='applied_users',
            field=models.ManyToManyField(related_name='job_applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
