# Generated by Django 5.0.2 on 2024-05-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_company', '0005_remove_job_application_form_applied_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_application_form',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
