# Generated by Django 5.0.2 on 2024-05-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_company', '0006_job_application_form_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interviewing_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interviewing', models.ManyToManyField(related_name='interview_forms', to='my_company.job_application_form')),
            ],
        ),
    ]
