# Generated by Django 5.0.2 on 2024-05-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_company', '0007_interviewing_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_application_form',
            name='interview',
            field=models.BooleanField(default=False),
        ),
    ]
