# Generated by Django 5.0.2 on 2024-05-10 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_company', '0008_job_application_form_interview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='departments',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='genders',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='teams',
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='my_company.department'),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='my_company.gender'),
        ),
        migrations.AddField(
            model_name='employee',
            name='team',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='my_company.team'),
        ),
        migrations.RemoveField(
            model_name='employee',
            name='positions',
        ),
        migrations.AddField(
            model_name='employee',
            name='positions',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='my_company.position'),
        ),
    ]
