# Generated by Django 5.0.2 on 2024-05-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_company', '0010_job_application_form_applying_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
