# Generated by Django 5.0.2 on 2024-05-30 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_company', '0011_employee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='positions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='team',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
