# Generated by Django 5.0.2 on 2024-06-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_company', '0012_alter_employee_department_alter_employee_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_application_form',
            name='expected_salary',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
