# Generated by Django 5.0.2 on 2024-06-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_company', '0013_alter_job_application_form_expected_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
