# Generated by Django 5.0.2 on 2024-06-19 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_company', '0014_alter_employee_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='user',
            new_name='applier',
        ),
    ]
